# API
api_bind = "127.0.0.1"
api_port = 9814

# RPC
rpc_bind = "127.0.0.1"
rpc_port = 8814

# bitcoind
btc_network = "bitcoin"
btc_rpc_user = "CSW"
btc_rpc_password = "NotSatoshi"
btc_rpc_connect = "localhost"
btc_rpc_port = 8332

# Flags
debug = false
overwrite_key = false

# General
subscription_slots = 10000
subscription_duration = 4320
expiry_delta = 6
min_to_self_delay = 20
polling_delta = 60

# Internal API
internal_api_bind = "127.0.0.1"
internal_api_port = 50051